# Test against the latest version of this Node.js version
environment:
  nodejs_version: "14"

# Install scripts. (runs after repo cloning)
install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

build_script:
  - npm run build
  - cd dist
  - 7z a dist.zip *
  - cd ..

artifacts:
  - path: dist\dist.zip
    name: Alphabot


test: off